### ISSUE TITLE
Git and docker persistent data causing issues

### ISSUE THREAD

**Issue by bryan-robitaille** [gctools-outilsgc/pleio_account#22]
Docker volumes or mount points are required to be empty upon instantiation by the posgres image.  Git requires that a file be present in the folder in order for it to be part of the repo structure.

A solution may be to build an initialization script for the first time running the docker image which empties or creates the posgres-data directory and then runs the docker-compose up --build.

**Comment by bryan-robitaille** [comment]
References commits: 
bbf0661b9f1092cfe6bcea70927c0faf33470f3b
670204e6d3332571e8b514f92706879bddc2b45e

**Comment by markwooff** [comment]
Should have been fixed with removing postgres-data directory and using different Docker version. Closing issue.
